#!/bin/sh
./pan4 -k4 -w28 -m10000 -h30 -RS227123 -c1 -x -n	# 2863.3 sec (+ 715.8 s, 32.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan8 -k3 -w28 -m10000 -h22 -c1 -x -n	# 5905.6 sec (+ 715.8 s, 32.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k2 -w28 -m128 -h68 -RS34360 -c1 -x -n	# 8947.8 sec (+ 715.8 s, 32.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan8 -k1 -w28 -m128 -h81 -c1 -x -n	# 11990.1 sec (+ 715.8 s, 32.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w26 -m10000 -h99 -RS72131 -c1 -x -n	# 13242.8 sec (+ 179.0 s, 8.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan8 -k1 -w25 -m10000 -h48 -c1 -x -n	# 13869.2 sec (+ 89.5 s, 4.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w24 -m10000 -h85 -RS135576 -c1 -x -n	# 14137.6 sec (+ 44.7 s, 2.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan8 -k1 -w23 -m10000 -h26 -c1 -x -n	# 14271.8 sec (+ 22.4 s, 1.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w22 -m10000 -h84 -RS103059 -c1 -x -n	# 14338.9 sec (+ 11.2 s, 0.5 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan8 -k1 -w21 -m10000 -h68 -c1 -x -n	# 14372.5 sec (+ 5.6 s, 0.2 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w20 -m10000 -h98 -RS35394 -c1 -x -n	# 14386.5 sec (+ 2.8 s, 0.1 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan8 -k1 -w19 -m10000 -h97 -c1 -x -n	# 14393.5 sec (+ 1.4 s, 0.1 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
date > swarm_done_s3
exit 1
