#!/bin/sh
./pan2 -k2 -w28 -m10000 -h13 -RS49839 -c1 -x -n	# 1431.7 sec (+ 715.8 s, 32.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan6 -k1 -w28 -m10000 -h31 -c1 -x -n	# 4473.9 sec (+ 715.8 s, 32.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan2 -k5 -w28 -m128 -h1 -RS33102 -c1 -x -n	# 7516.2 sec (+ 894.8 s, 32.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan6 -k4 -w28 -m128 -h91 -c1 -x -n	# 10379.5 sec (+ 715.8 s, 32.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan2 -k1 -w27 -m10000 -h93 -RS138509 -c1 -x -n	# 12705.9 sec (+ 357.9 s, 16.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan6 -k1 -w26 -m10000 -h76 -c1 -x -n	# 13600.7 sec (+ 179.0 s, 8.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan2 -k1 -w25 -m10000 -h72 -RS42557 -c1 -x -n	# 14048.1 sec (+ 89.5 s, 4.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan6 -k1 -w24 -m10000 -h31 -c1 -x -n	# 14227.1 sec (+ 44.7 s, 2.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan2 -k1 -w23 -m10000 -h16 -RS23102 -c1 -x -n	# 14316.6 sec (+ 22.4 s, 1.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan6 -k1 -w22 -m10000 -h7 -c1 -x -n	# 14361.3 sec (+ 11.2 s, 0.5 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan2 -k1 -w20 -m10000 -h13 -RS24949 -c1 -x -n	# 14380.9 sec (+ 2.8 s, 0.1 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan6 -k1 -w19 -m10000 -h74 -c1 -x -n	# 14390.7 sec (+ 1.4 s, 0.1 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
date > swarm_done_s1
exit 1
