#!/bin/sh
./pan4 -k1 -w29 -m10000 -h16 -RS72131 	# 24338.1 sec (+ 1431.7 s, 64.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w28 -m10000 -h48 -RS120615 	# 41518.0 sec (+ 715.8 s, 32.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w27 -m10000 -h11 -RS29182 	# 49750.0 sec (+ 357.9 s, 16.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w26 -m10000 -h82 -RS137058 	# 53687.1 sec (+ 179.0 s, 8.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w25 -m10000 -h16 -RS142830 	# 55655.6 sec (+ 89.5 s, 4.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w24 -m10000 -h74 -RS174267 	# 56639.9 sec (+ 44.7 s, 2.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w23 -m10000 -h50 -RS260061 	# 57132.0 sec (+ 22.4 s, 1.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w22 -m10000 -h5 -RS260880 	# 57366.9 sec (+ 11.2 s, 0.5 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w21 -m10000 -h68 -RS38098 	# 57484.3 sec (+ 5.6 s, 0.2 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w20 -m10000 -h20 -RS253142 	# 57543.1 sec (+ 2.8 s, 0.1 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w19 -m10000 -h79 -RS54673 	# 57572.4 sec (+ 1.4 s, 0.1 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
date > swarm_done_s11
exit 1
