#!/bin/sh
./pan4 -k1 -w30 -m10000 -h31 -RS227123 	# 11453.2 sec (+ 2863.3 s, 128.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w29 -m10000 -h99 -RS103059 	# 35791.4 sec (+ 1431.7 s, 64.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w27 -m10000 -h80 -RS59097 	# 46886.7 sec (+ 357.9 s, 16.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w26 -m10000 -h97 -RS167229 	# 52255.4 sec (+ 179.0 s, 8.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w25 -m10000 -h42 -RS60970 	# 54939.8 sec (+ 89.5 s, 4.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w24 -m10000 -h68 -RS213112 	# 56282.0 sec (+ 44.7 s, 2.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w23 -m10000 -h89 -RS56447 	# 56953.1 sec (+ 22.4 s, 1.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w22 -m10000 -h92 -RS18348 	# 57277.4 sec (+ 11.2 s, 0.5 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w21 -m10000 -h4 -RS195527 	# 57439.6 sec (+ 5.6 s, 0.2 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w20 -m10000 -h68 -RS34725 	# 57520.7 sec (+ 2.8 s, 0.1 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w19 -m10000 -h96 -RS135966 	# 57561.2 sec (+ 1.4 s, 0.1 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
date > swarm_done_s3
exit 1
