#!/bin/sh
./pan2 -k1 -w29 -m10000 -h9 -RS42557 	# 27201.5 sec (+ 1431.7 s, 64.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan2 -k1 -w28 -m10000 -h58 -RS231197 	# 42949.7 sec (+ 715.8 s, 32.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan2 -k1 -w27 -m10000 -h13 -RS245742 	# 50465.9 sec (+ 357.9 s, 16.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan2 -k1 -w26 -m10000 -h59 -RS195883 	# 54045.0 sec (+ 179.0 s, 8.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan2 -k1 -w25 -m10000 -h84 -RS92896 	# 55834.6 sec (+ 89.5 s, 4.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan2 -k1 -w24 -m10000 -h25 -RS152172 	# 56729.4 sec (+ 44.7 s, 2.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan2 -k1 -w23 -m10000 -h81 -RS234832 	# 57176.8 sec (+ 22.4 s, 1.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan2 -k1 -w22 -m10000 -h78 -RS139262 	# 57389.3 sec (+ 11.2 s, 0.5 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan2 -k1 -w21 -m10000 -h0 -RS171426 	# 57495.5 sec (+ 5.6 s, 0.2 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan2 -k1 -w20 -m10000 -h16 -RS248172 	# 57548.6 sec (+ 2.8 s, 0.1 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan2 -k1 -w19 -m10000 -h98 -RS204846 	# 57575.2 sec (+ 1.4 s, 0.1 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
date > swarm_done_s13
exit 1
