#!/bin/sh
./pan2 -k1 -w30 -m10000 -h30 -RS49839 	# 5726.6 sec (+ 2863.3 s, 128.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan2 -k1 -w29 -m10000 -h26 -RS23102 	# 32928.1 sec (+ 1431.7 s, 64.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan2 -k1 -w28 -m10000 -h26 -RS30932 	# 45813.0 sec (+ 715.8 s, 32.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan2 -k1 -w27 -m10000 -h81 -RS26838 	# 51897.5 sec (+ 357.9 s, 16.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan2 -k1 -w26 -m10000 -h41 -RS94707 	# 54760.8 sec (+ 179.0 s, 8.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan2 -k1 -w25 -m10000 -h46 -RS68483 	# 56192.5 sec (+ 89.5 s, 4.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan2 -k1 -w24 -m10000 -h9 -RS59026 	# 56908.3 sec (+ 44.7 s, 2.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan2 -k1 -w22 -m10000 -h72 -RS151538 	# 57255.0 sec (+ 11.2 s, 0.5 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan2 -k1 -w21 -m10000 -h84 -RS234162 	# 57428.4 sec (+ 5.6 s, 0.2 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan2 -k1 -w20 -m10000 -h0 -RS163965 	# 57515.1 sec (+ 2.8 s, 0.1 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan2 -k1 -w19 -m10000 -h56 -RS49401 	# 57558.4 sec (+ 1.4 s, 0.1 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
date > swarm_done_s1
exit 1
