#!/bin/sh
./pan3 -k1 -w29 -m10000 -h91 -RS21239 	# 22906.5 sec (+ 1431.7 s, 64.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan3 -k1 -w28 -m10000 -h85 -RS221887 	# 40802.2 sec (+ 715.8 s, 32.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan3 -k1 -w27 -m10000 -h68 -RS201893 	# 49392.1 sec (+ 357.9 s, 16.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan3 -k1 -w26 -m10000 -h69 -RS259014 	# 53508.1 sec (+ 179.0 s, 8.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan3 -k1 -w25 -m10000 -h71 -RS16263 	# 55566.1 sec (+ 89.5 s, 4.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan3 -k1 -w24 -m10000 -h98 -RS11010 	# 56595.1 sec (+ 44.7 s, 2.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan3 -k1 -w23 -m10000 -h1 -RS192680 	# 57109.6 sec (+ 22.4 s, 1.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan3 -k1 -w22 -m10000 -h38 -RS171589 	# 57355.7 sec (+ 11.2 s, 0.5 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan3 -k1 -w21 -m10000 -h36 -RS226139 	# 57478.7 sec (+ 5.6 s, 0.2 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan3 -k1 -w20 -m10000 -h30 -RS253182 	# 57540.3 sec (+ 2.8 s, 0.1 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan3 -k1 -w19 -m10000 -h99 -RS74527 	# 57571.0 sec (+ 1.4 s, 0.1 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
date > swarm_done_s10
exit 1
