#!/bin/sh
./pan3 -k1 -w30 -m10000 -h79 -RS65803 	# 8589.9 sec (+ 2863.3 s, 128.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan3 -k1 -w29 -m10000 -h65 -RS24360 	# 34359.7 sec (+ 1431.7 s, 64.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan3 -k1 -w28 -m10000 -h39 -RS45933 	# 46528.8 sec (+ 715.8 s, 32.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan3 -k1 -w26 -m10000 -h43 -RS76825 	# 52076.5 sec (+ 179.0 s, 8.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan3 -k1 -w25 -m10000 -h63 -RS147209 	# 54850.3 sec (+ 89.5 s, 4.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan3 -k1 -w24 -m10000 -h31 -RS100277 	# 56237.2 sec (+ 44.7 s, 2.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan3 -k1 -w23 -m10000 -h55 -RS171968 	# 56930.7 sec (+ 22.4 s, 1.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan3 -k1 -w22 -m10000 -h47 -RS188979 	# 57266.2 sec (+ 11.2 s, 0.5 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan3 -k1 -w21 -m10000 -h67 -RS249209 	# 57434.0 sec (+ 5.6 s, 0.2 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan3 -k1 -w20 -m10000 -h59 -RS134710 	# 57517.9 sec (+ 2.8 s, 0.1 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan3 -k1 -w19 -m10000 -h3 -RS69161 	# 57559.8 sec (+ 1.4 s, 0.1 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
date > swarm_done_s2
exit 1
