#!/bin/sh
./pan1 -k1 -w29 -m10000 -h68 -RS181059 	# 20043.2 sec (+ 1431.7 s, 64.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan1 -k1 -w28 -m10000 -h55 -RS143869 	# 39370.5 sec (+ 715.8 s, 32.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan1 -k1 -w27 -m10000 -h52 -RS123882 	# 48676.3 sec (+ 357.9 s, 16.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan1 -k1 -w26 -m10000 -h99 -RS170375 	# 53150.2 sec (+ 179.0 s, 8.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan1 -k1 -w25 -m10000 -h26 -RS55496 	# 55387.2 sec (+ 89.5 s, 4.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan1 -k1 -w24 -m10000 -h65 -RS134060 	# 56505.7 sec (+ 44.7 s, 2.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan1 -k1 -w23 -m10000 -h49 -RS137315 	# 57064.9 sec (+ 22.4 s, 1.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan1 -k1 -w22 -m10000 -h38 -RS21062 	# 57333.3 sec (+ 11.2 s, 0.5 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan1 -k1 -w21 -m10000 -h19 -RS180690 	# 57467.6 sec (+ 5.6 s, 0.2 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan1 -k1 -w20 -m10000 -h54 -RS24611 	# 57534.7 sec (+ 2.8 s, 0.1 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan1 -k1 -w19 -m10000 -h94 -RS72466 	# 57568.2 sec (+ 1.4 s, 0.1 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
date > swarm_done_s8
exit 1
