#!/bin/sh
./pan4 -k1 -w29 -m10000 -h24 -RS34360 	# 18611.5 sec (+ 1431.7 s, 64.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w28 -m10000 -h48 -RS35394 	# 38654.7 sec (+ 715.8 s, 32.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w27 -m10000 -h7 -RS220251 	# 48318.4 sec (+ 357.9 s, 16.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w26 -m10000 -h59 -RS77501 	# 52971.3 sec (+ 179.0 s, 8.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w25 -m10000 -h58 -RS199123 	# 55297.7 sec (+ 89.5 s, 4.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w24 -m10000 -h39 -RS222665 	# 56460.9 sec (+ 44.7 s, 2.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w23 -m10000 -h65 -RS179508 	# 57042.5 sec (+ 22.4 s, 1.0 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w22 -m10000 -h61 -RS106775 	# 57322.2 sec (+ 11.2 s, 0.5 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w21 -m10000 -h2 -RS6739 	# 57462.0 sec (+ 5.6 s, 0.2 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w20 -m10000 -h52 -RS94489 	# 57531.9 sec (+ 2.8 s, 0.1 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
./pan4 -k1 -w19 -m10000 -h98 -RS25777 	# 57566.8 sec (+ 1.4 s, 0.1 MB)
if [ -f swarm_times_up ] ; then exit 1; fi
date > swarm_done_s7
exit 1
